package db

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Store provides all functions to execute db queries and transactions.
// It wraps the generated Queries struct and adds transaction support.
type Store struct {
	*Queries               // embeds all query methods generated by sqlc
	connPool *pgxpool.Pool // connection pool to PostgreSQL
}

// NewStore creates a new Store instance.
// It initializes both the connection pool and the query layer.
func NewStore(connPool *pgxpool.Pool) *Store {
	return &Store{
		connPool: connPool,
		Queries:  New(connPool), // pass pool to sqlc-generated Queries
	}
}

// execTx executes a function within a database transaction.
//
// Pattern:
// 1. Begin transaction
// 2. Create a Queries instance bound to that transaction
// 3. Execute all DB operations through that instance
// 4. Rollback if error, Commit if success
//
// This ensures ALL operations inside fn are atomic (all succeed or all fail).
func (store *Store) execTx(ctx context.Context, fn func(*Queries) error) error {
	// Start a new transaction
	tx, err := store.connPool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return err
	}

	// Create a query object that uses this transaction instead of the pool
	q := New(tx)

	// Execute the callback function
	err = fn(q)
	if err != nil {
		// If anything fails, rollback the transaction
		if rbErr := tx.Rollback(ctx); rbErr != nil {
			// Return BOTH the original error and rollback error for debugging
			return fmt.Errorf("tx err: %v, rb err: %v", err, rbErr)
		}
		return err
	}

	// If everything succeeds, commit the transaction
	return tx.Commit(ctx)
}

// TransferTxParams contains the input data for a transfer transaction.
type TransferTxParams struct {
	FromAccountID int64 `json:"from_account_id"` // sender account
	ToAccountID   int64 `json:"to_account_id"`   // receiver account
	Amount        int64 `json:"amount"`          // amount to transfer
}

// TransferTxResult contains all results produced by the transaction.
// This is useful for testing and debugging.
type TransferTxResult struct {
	Transfer    Transfer `json:"transfer"`     // transfer record
	FromAccount Account  `json:"from_account"` // updated sender account
	ToAccount   Account  `json:"to_account"`   // updated receiver account
	FromEntry   Entry    `json:"from_entry"`   // debit entry
	ToEntry     Entry    `json:"to_entry"`     // credit entry
}



// TransferTx performs a money transfer between two accounts.
//
// Steps:
// 1. Create a transfer record
// 2. Create debit entry (from account)
// 3. Create credit entry (to account)
// 4. Update both account balances
//
// IMPORTANT:
// All of this runs inside ONE transaction → guarantees consistency.
// If any step fails, everything is rolled back.
func (store *Store) TransferTx(ctx context.Context, arg TransferTxParams) (TransferTxResult, error) {
	var result TransferTxResult

	// Execute all operations inside a transaction
	err := store.execTx(ctx, func(q *Queries) error {
		var err error



		// Step 1: Create transfer record
		result.Transfer, err = q.CreateTransfer(ctx, CreateTransferParams{
			FromAccountID: arg.FromAccountID,
			ToAccountID:   arg.ToAccountID,
			Amount:        arg.Amount,
		})
		if err != nil {
			return err
		}

		// Step 2: Create entry for sender (money goes OUT → negative)
		
		result.FromEntry, err = q.CreateEntry(ctx, CreateEntryParams{
			AccountID: arg.FromAccountID,
			Amount:    -arg.Amount,
		})
		if err != nil {
			return err
		}

		// Step 3: Create entry for receiver (money comes IN → positive)
		
		result.ToEntry, err = q.CreateEntry(ctx, CreateEntryParams{
			AccountID: arg.ToAccountID,
			Amount:    arg.Amount,
		})
		if err != nil {
			return err
		}

		// Step 4: Update account balances manually
		// NOTE: This approach reads the current balance first, then updates it.
		// (Later in the tutorial, this will be improved to avoid race conditions.)

		// Get sender account
		
		account1, err := q.GetAccountForUpdate(ctx, arg.FromAccountID)
		if err != nil {
			return err
		}

		

		// Update sender balance (subtract amount)
		
		result.FromAccount, err = q.UpdateAccount(ctx, UpdateAccountParams{
			ID:      account1.ID,
			Balance: account1.Balance - arg.Amount,
		})
		if err != nil {
			return err
		}

		// Get receiver account
		
		account2, err := q.GetAccountForUpdate(ctx, arg.ToAccountID)
		if err != nil {
			return err
		}

		// Update receiver balance (add amount)
		
		result.ToAccount, err = q.UpdateAccount(ctx, UpdateAccountParams{
			ID:      account2.ID,
			Balance: account2.Balance + arg.Amount,
		})
		if err != nil {
			return err
		}

		return nil
	})

	return result, err
}